name: Release Management

on:
  repository_dispatch:
    types:
      - jira-release-approved

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Print Release Payload
        run: |
          echo "Release Version:"
          echo "${{ github.event.client_payload.release_version }}"

          echo "Environment:"
          echo "${{ github.event.client_payload.environment }}"
